---

- hosts: local

  roles:
    - homebrew_setting

  # tasks:
  #   - name: install cask packages
  #     homebrew_cask:
  #       name: "{{ item }}"
  #     loop:
  #       - 1password
  #       - google-chrome
  #       - slack
  #       - zoom
  #       - discord
  #       - miro
  #       - visual-studio-code
  #       - github
  #       - docker
  #       - font-noto-sans-cjk
